name: 'Deploy to Dokploy'
description: 'Deploy to Dokploy'
author: 'wyattjoh'
inputs:
  url:
    description: 'The Dokploy URL'
    required: true
    default: 'https://panel.dokploy.com'
  token:
    description: 'The Dokploy token'
    required: true
  project-id:
    description: 'The project ID to deploy'
    required: true
  compose-id:
    description: 'The compose ID to deploy'
    required: true
runs:
  using: node20
  main: dist/index.js
